
[[pages]]
path = "streamlit_app/st_pages/broad_mkt.py"
name = "Broad Market"

[[pages]]
path = "streamlit_app/st_pages/sector.py"
name = "Sector Analysis"

[[pages]]
path = "streamlit_app/streamlit_app.py"
name = "Stock Analysis"

[[pages]]
path = "streamlit_app/st_pages/glossary.py"
name =  "Glossary"